site_name: matamata
site_description: >-
  Model tournament knockout stages in JSON format and render the schedule in
  SVG or html table format
site_url: https://anibalpacheco.github.io/matamata/
repo_url: https://github.com/anibalpacheco/matamata
edit_uri: blob/main/docs/

nav:
  - Documentation: index.md
  - Format specification: format.md

theme:
  name: readthedocs

